//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/BicycleControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BicycleControlsA: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BicycleControlsA()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BicycleControls"",
    ""maps"": [
        {
            ""name"": ""Bicycle"",
            ""id"": ""62cf6dab-2bb4-4456-8b2c-5683e1bfed90"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""f802b8c1-530b-4b64-a045-0a1c696b289f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Button"",
                    ""id"": ""c17d3a48-f594-4e84-823b-30b8e9943c56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""4c920a41-21be-4e1b-b0e5-81bfdd77c97f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Move"",
                    ""id"": ""7f643b84-c574-4001-a327-11a9201f8b4f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""add71d5e-cbbe-4fa5-8407-217f18a765c8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5ea4c286-7ce2-4b55-ab8e-441c707c51eb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""87c4cc2a-dfd9-4f1b-b02b-a3dd114ee541"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e27b1568-dc58-495f-aa26-f4d28caf6b45"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""721f56b5-b650-40fd-8dab-1c3b2b42e7c0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c24b970d-e8a3-4de8-b958-e54d5ea3d487"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Bicycle
        m_Bicycle = asset.FindActionMap("Bicycle", throwIfNotFound: true);
        m_Bicycle_Move = m_Bicycle.FindAction("Move", throwIfNotFound: true);
        m_Bicycle_Brake = m_Bicycle.FindAction("Brake", throwIfNotFound: true);
        m_Bicycle_Interact = m_Bicycle.FindAction("Interact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Bicycle
    private readonly InputActionMap m_Bicycle;
    private List<IBicycleActions> m_BicycleActionsCallbackInterfaces = new List<IBicycleActions>();
    private readonly InputAction m_Bicycle_Move;
    private readonly InputAction m_Bicycle_Brake;
    private readonly InputAction m_Bicycle_Interact;
    public struct BicycleActions
    {
        private @BicycleControlsA m_Wrapper;
        public BicycleActions(@BicycleControlsA wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Bicycle_Move;
        public InputAction @Brake => m_Wrapper.m_Bicycle_Brake;
        public InputAction @Interact => m_Wrapper.m_Bicycle_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Bicycle; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BicycleActions set) { return set.Get(); }
        public void AddCallbacks(IBicycleActions instance)
        {
            if (instance == null || m_Wrapper.m_BicycleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BicycleActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IBicycleActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IBicycleActions instance)
        {
            if (m_Wrapper.m_BicycleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBicycleActions instance)
        {
            foreach (var item in m_Wrapper.m_BicycleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BicycleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BicycleActions @Bicycle => new BicycleActions(this);
    public interface IBicycleActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
}
