//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/MotorcycleControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MotorcycleControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MotorcycleControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MotorcycleControls"",
    ""maps"": [
        {
            ""name"": ""Motorcycle"",
            ""id"": ""102ab894-5568-4dee-865d-572e163787ec"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""751bfac1-a627-4a04-9dea-782aa8dd46ea"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Button"",
                    ""id"": ""87b1a9be-f102-4feb-9b7a-0d266ef9e46e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""cd813bcc-0bff-4edb-82ba-d5ee3aecc94c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e91d9506-6f45-4dcd-91c2-b51e40a77a7c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""339c0aee-d02c-4b0a-8a19-0ca89eee2e06"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e33ceab1-2461-4f40-b33b-0c2addd56ea8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cd647ede-fbad-451b-a6cf-df7a907bb691"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2d278b57-0144-4e7e-8b05-99d5e1ff3967"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""916d8c29-096b-4520-a889-894bed96d489"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d021adb0-222c-48bd-9fb1-112acc6c02ab"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Motorcycle
        m_Motorcycle = asset.FindActionMap("Motorcycle", throwIfNotFound: true);
        m_Motorcycle_Move = m_Motorcycle.FindAction("Move", throwIfNotFound: true);
        m_Motorcycle_Brake = m_Motorcycle.FindAction("Brake", throwIfNotFound: true);
        m_Motorcycle_Interact = m_Motorcycle.FindAction("Interact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Motorcycle
    private readonly InputActionMap m_Motorcycle;
    private List<IMotorcycleActions> m_MotorcycleActionsCallbackInterfaces = new List<IMotorcycleActions>();
    private readonly InputAction m_Motorcycle_Move;
    private readonly InputAction m_Motorcycle_Brake;
    private readonly InputAction m_Motorcycle_Interact;
    public struct MotorcycleActions
    {
        private @MotorcycleControls m_Wrapper;
        public MotorcycleActions(@MotorcycleControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Motorcycle_Move;
        public InputAction @Brake => m_Wrapper.m_Motorcycle_Brake;
        public InputAction @Interact => m_Wrapper.m_Motorcycle_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Motorcycle; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MotorcycleActions set) { return set.Get(); }
        public void AddCallbacks(IMotorcycleActions instance)
        {
            if (instance == null || m_Wrapper.m_MotorcycleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MotorcycleActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IMotorcycleActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IMotorcycleActions instance)
        {
            if (m_Wrapper.m_MotorcycleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMotorcycleActions instance)
        {
            foreach (var item in m_Wrapper.m_MotorcycleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MotorcycleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MotorcycleActions @Motorcycle => new MotorcycleActions(this);
    public interface IMotorcycleActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
}
